import { User } from '../models/user.model';

export const titles = [
  'Faire les courses',
  'Faire le ménage',
  'Tondre la pelouse',
  'Ranger la chambre',
  'Faire ses devoirs',
];
export const images = [
  'food-shop.webp',
  'cleaning.jpg',
  'rangement.jpg',
  'tondeuse.jpg',
  'study.jpeg',
];
export const completed = [false, true];
export const countries = [
  'Canada',
  'United States',
  'Mexico',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Venezuela',
  'Germany',
  'France',
  'United Kingdom',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Portugal',
  'Ireland',
  'Greece',
  'Turkey',
  'Russia',
  'China',
  'India',
  'Japan',
  'South Korea',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Australia',
  'New Zealand',
  'South Africa',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Saudi Arabia',
  'United Arab Emirates',
  'Israel',
  'Pakistan',
  'Bangladesh',
  'Malaysia',
  'Singapore',
];
